const perguntas = [
  // NIVEL FACIL
  { nivel: "facil", pergunta: "O que e musica?", opcoes: ["Som organizado", "Barulho aleatorio", "Silencio total", "Imagem"], resposta: 0 },
  { nivel: "facil", pergunta: "Qual e um elemento da musica?", opcoes: ["Cor", "Ritmo", "Cheiro", "Luz"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e ritmo?", opcoes: ["Altura", "Organizacao no tempo", "Volume", "Nota"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e melodia?", opcoes: ["Som unico", "Sequencia de notas", "Silencio", "Barulho"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e harmonia?", opcoes: ["Uma nota", "Sons simultaneos", "Silencio", "Ritmo"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e som?", opcoes: ["Algo que ouvimos", "Algo que vemos", "Algo que tocamos", "Algo que cheiramos"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e intensidade?", opcoes: ["Altura", "Forca do som", "Tempo", "Nota"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e timbre?", opcoes: ["Altura", "Cor do som", "Tempo", "Volume"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e altura do som?", opcoes: ["Forte ou fraco", "Grave ou agudo", "Rapido ou lento", "Longo ou curto"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e duracao?", opcoes: ["Altura", "Tempo do som", "Volume", "Timbre"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e silencio na musica?", opcoes: ["Som forte", "Ausencia de som", "Melodia", "Ritmo"], resposta: 1 },
  { nivel: "facil", pergunta: "O silencio faz parte da musica?", opcoes: ["Sim", "Nao", "As vezes", "Nunca"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e pulsacao?", opcoes: ["Altura", "Batida regular", "Volume", "Nota"], resposta: 1 },
  { nivel: "facil", pergunta: "Qual elemento organiza o tempo?", opcoes: ["Ritmo", "Altura", "Timbre", "Intensidade"], resposta: 0 },
  { nivel: "facil", pergunta: "Qual elemento e sequencia de notas?", opcoes: ["Melodia", "Ritmo", "Timbre", "Volume"], resposta: 0 },
  { nivel: "facil", pergunta: "Qual elemento combina sons ao mesmo tempo?", opcoes: ["Harmonia", "Ritmo", "Altura", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que define se o som e forte ou fraco?", opcoes: ["Altura", "Intensidade", "Ritmo", "Timbre"], resposta: 1 },
  { nivel: "facil", pergunta: "O que diferencia instrumentos?", opcoes: ["Ritmo", "Timbre", "Tempo", "Altura"], resposta: 1 },
  { nivel: "facil", pergunta: "O que e andamento?", opcoes: ["Altura", "Velocidade", "Volume", "Nota"], resposta: 1 },
  { nivel: "facil", pergunta: "Musica rapida tem andamento:", opcoes: ["Lento", "Rapido", "Grave", "Alto"], resposta: 1 },
  { nivel: "facil", pergunta: "Musica lenta tem andamento:", opcoes: ["Rapido", "Lento", "Forte", "Agudo"], resposta: 1 },
  { nivel: "facil", pergunta: "Qual elemento e base da musica?", opcoes: ["Som", "Cor", "Imagem", "Luz"], resposta: 0 },
  { nivel: "facil", pergunta: "Qual NAO e elemento musical?", opcoes: ["Ritmo", "Melodia", "Cor", "Harmonia"], resposta: 2 },
  { nivel: "facil", pergunta: "Musica usa:", opcoes: ["Som e silencio", "Cor", "Cheiro", "Luz"], resposta: 0 },
  { nivel: "facil", pergunta: "A musica acontece no:", opcoes: ["Tempo", "Espaco", "Cor", "Luz"], resposta: 0 },

  // NIVEL MEDIO
  { nivel: "medio", pergunta: "Quantos semitons existem em uma oitava?", opcoes: ["6", "8", "12", "14"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantos semitons tem um tom?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantos semitons tem um semitom?", opcoes: ["1", "2", "3", "4"], resposta: 0 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Re?", opcoes: ["1 semitom", "1 tom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual intervalo entre Mi e Fa?", opcoes: ["1 tom", "1 semitom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantos graus tem a escala diatonica?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "medio", pergunta: "Qual e a formula da escala maior?", opcoes: ["T T ST T T T ST", "T ST T T ST T T", "ST T T T ST T T", "T T T ST T ST T"], resposta: 0 },
  { nivel: "medio", pergunta: "Quantos tempos tem o compasso 4/4?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantos tempos tem o compasso 3/4?", opcoes: ["2", "3", "4", "5"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual figura vale 1 tempo no 4/4?", opcoes: ["Semibreve", "Minima", "Seminima", "Colcheia"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantas colcheias cabem em uma seminima?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", pergunta: "O sustenido (#) altera:", opcoes: ["1 tom", "1 semitom acima", "1 semitom abaixo", "2 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "O bemol (b) altera:", opcoes: ["1 tom", "1 semitom abaixo", "1 semitom acima", "2 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantas linhas tem a pauta?", opcoes: ["4", "5", "6", "7"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual clave indica sons graves?", opcoes: ["Sol", "Fa", "Do", "Neutra"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantas seminimas cabem em uma semibreve?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Mi?", opcoes: ["Segunda", "Terca", "Quarta", "Quinta"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Sol?", opcoes: ["Quarta", "Quinta", "Sexta", "Setima"], resposta: 1 },

  // NIVEL DIFICIL
  { nivel: "dificil", pergunta: "Quantos tons tem a escala maior?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "dificil", pergunta: "Quantos tons tem a escala menor natural?", opcoes: ["3", "4", "5", "6"], resposta: 1 },
  { nivel: "dificil", pergunta: "Quantos semitons tem a escala menor natural?", opcoes: ["10", "11", "12", "7"], resposta: 2 },
  { nivel: "dificil", pergunta: "Qual e a formula da escala menor natural?", opcoes: ["T ST T T ST T T", "T T ST T T T ST", "ST T T ST T T T", "T T T ST T ST T"], resposta: 0 },
  { nivel: "dificil", pergunta: "Uma triade tem quantas notas?", opcoes: ["2", "3", "4", "5"], resposta: 1 },
  { nivel: "dificil", pergunta: "Triade maior possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 0 },
  { nivel: "dificil", pergunta: "Triade menor possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 1 },
  { nivel: "dificil", pergunta: "O V grau tem funcao:", opcoes: ["Tonica", "Dominante", "Subdominante", "Relativa"], resposta: 1 },
  { nivel: "dificil", pergunta: "O I grau tem funcao:", opcoes: ["Dominante", "Tonica", "Subdominante", "Sensivel"], resposta: 1 },
  { nivel: "dificil", pergunta: "Cadencia V-I e:", opcoes: ["Imperfeita", "Perfeita", "Plagal", "Deceptiva"], resposta: 1 },
  { nivel: "dificil", pergunta: "Quantos semitons tem uma quinta justa?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "dificil", pergunta: "Quantos semitons tem uma terca maior?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "dificil", pergunta: "O que e enarmonia?", opcoes: ["Mesmo som, nomes diferentes", "Notas diferentes", "Intervalos iguais", "Acordes iguais"], resposta: 0 },
  { nivel: "dificil", pergunta: "O que e modulacao?", opcoes: ["Mudanca de ritmo", "Mudanca de tonalidade", "Mudanca de intensidade", "Mudanca de timbre"], resposta: 1 },
];

module.exports = { perguntas };
