const TOPICOS = [
  { id: "teoria-musical",      label: "Teoria Musical" },
  { id: "harmonia-funcional",  label: "Harmonia Funcional" },
  { id: "historia-da-musica",  label: "Historia da Musica" },
];

const perguntas = [
  // NIVEL FACIL — Teoria Musical
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e musica?", opcoes: ["Organizacao de sons e silencio no tempo", "Som aleatorio sem organizacao", "Apenas repeticao de ritmos", "Som sem duracao definida"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e ritmo?", opcoes: ["Altura dos sons musicais", "Organizacao dos sons no tempo", "Volume dos sons musicais", "Tipo de instrumento"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e melodia?", opcoes: ["Sequencia de notas organizadas no tempo", "Varios sons tocados ao mesmo tempo", "Som sem altura definida", "Organizacao dos tempos"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e harmonia?", opcoes: ["Sequencia de notas isoladas", "Combinacao de sons simultaneos", "Silencio entre sons", "Velocidade da musica"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e intensidade?", opcoes: ["Altura do som", "Duracao do som", "Forca do som", "Sequencia de notas"], resposta: 2 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e altura do som?", opcoes: ["Volume do som", "Grave ou agudo", "Tempo do som", "Duracao do som"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e timbre?", opcoes: ["Caracteristica que diferencia os sons", "Altura do som", "Duracao do som", "Velocidade da musica"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e duracao?", opcoes: ["Tempo que o som permanece", "Altura do som", "Forca do som", "Tipo de instrumento"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e pulsacao?", opcoes: ["Batida regular da musica", "Altura das notas", "Volume do som", "Tipo de acorde"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e andamento?", opcoes: ["Velocidade da musica", "Altura das notas", "Duracao do som", "Timbre do instrumento"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e pentagrama?", opcoes: ["Conjunto de quatro linhas", "Conjunto de cinco linhas", "Sequencia de notas", "Tipo de compasso"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "Para que serve o pentagrama?", opcoes: ["Definir o ritmo da musica", "Registrar e organizar as notas musicais", "Aumentar o volume do som", "Definir a velocidade"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e clave?", opcoes: ["Figura que determina o silencio das notas no pentagrama", "Figura que determina a duracao das notas", "Figura que determina a altura e o nome das notas no pentagrama", "Figura que determina o ritmo da musica"], resposta: 2 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "Para que serve a clave de Sol?", opcoes: ["Determinar notas graves", "Determinar notas agudas", "Determinar o ritmo", "Determinar o silencio"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "Para que serve a clave de Fa?", opcoes: ["Determinar notas agudas", "Determinar notas graves", "Determinar o ritmo", "Determinar o andamento"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e nota musical?", opcoes: ["Representacao grafica do som", "Representacao do silencio", "Organizacao do tempo", "Tipo de instrumento"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e figura musical?", opcoes: ["Representacao da altura do som", "Representacao da duracao do som", "Representacao do timbre", "Representacao da intensidade"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e pausa?", opcoes: ["Representacao do silencio na musica", "Representacao da altura", "Representacao da duracao do som", "Representacao do ritmo"], resposta: 0 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "Para que servem as figuras musicais?", opcoes: ["Indicar a altura das notas", "Indicar a duracao dos sons", "Indicar o timbre", "Indicar o instrumento"], resposta: 1 },
  { nivel: "facil", topico: "teoria-musical", pergunta: "O que e compasso?", opcoes: ["Organizacao dos tempos em grupos", "Altura das notas", "Tipo de som", "Timbre do instrumento"], resposta: 0 },

  // NIVEL MEDIO — Teoria Musical
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos semitons existem em uma oitava?", opcoes: ["6", "8", "12", "14"], resposta: 2 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos semitons tem um tom?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos semitons tem um semitom?", opcoes: ["1", "2", "3", "4"], resposta: 0 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual intervalo entre Do e Re?", opcoes: ["1 semitom", "1 tom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual intervalo entre Mi e Fa?", opcoes: ["1 tom", "1 semitom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos graus tem a escala diatonica?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual e a formula da escala maior?", opcoes: ["T T ST T T T ST", "T ST T T ST T T", "ST T T T ST T T", "T T T ST T ST T"], resposta: 0 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos tempos tem o compasso 4/4?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantos tempos tem o compasso 3/4?", opcoes: ["2", "3", "4", "5"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual figura vale 1 tempo no 4/4?", opcoes: ["Semibreve", "Minima", "Seminima", "Colcheia"], resposta: 2 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantas colcheias cabem em uma seminima?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "O sustenido (#) altera:", opcoes: ["1 tom", "1 semitom acima", "1 semitom abaixo", "2 tons"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "O bemol (b) altera:", opcoes: ["1 tom", "1 semitom abaixo", "1 semitom acima", "2 tons"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantas linhas tem a pauta?", opcoes: ["4", "5", "6", "7"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual clave indica sons graves?", opcoes: ["Sol", "Fa", "Do", "Neutra"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Quantas seminimas cabem em uma semibreve?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual intervalo entre Do e Mi?", opcoes: ["Segunda", "Terca", "Quarta", "Quinta"], resposta: 1 },
  { nivel: "medio", topico: "teoria-musical", pergunta: "Qual intervalo entre Do e Sol?", opcoes: ["Quarta", "Quinta", "Sexta", "Setima"], resposta: 1 },

  // NIVEL DIFICIL — Harmonia Funcional
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Quantos tons tem a escala maior?", opcoes: ["5", "6", "7", "8"], resposta: 2, explicacoes: ["Incorreto. 5 tons nao completa a estrutura da escala maior, que precisa fechar uma oitava completa.", "Incorreto. 6 tons esta proximo, mas ignora que a escala tambem possui semitons estruturais obrigatorios.", "Correto. A escala maior e formada por 6 tons e 2 semitons (12 semitons no total). O essencial e entender a distribuicao: T-T-ST-T-T-T-ST.", "Incorreto. 8 representa quantidade de notas (graus), nao a soma intervalar em tons."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Quantos tons tem a escala menor natural?", opcoes: ["3", "4", "5", "6"], resposta: 2, explicacoes: ["Incorreto. 3 tons nao sustenta uma estrutura diatonica.", "Incorreto. 4 tons e uma contagem incompleta comum, mas nao corresponde a realidade.", "Correto. A escala menor natural possui 5 tons e 2 semitons, totalizando 12 semitons.", "Incorreto. 6 tons descaracteriza o modo menor."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Quantos semitons tem a escala menor natural?", opcoes: ["10", "11", "12", "7"], resposta: 2, explicacoes: ["Incorreto. 10 semitons nao completam a oitava.", "Incorreto. 11 semitons nao formam uma oitava completa.", "Correto. Toda escala dentro da oitava possui 12 semitons.", "Incorreto. 7 refere-se a numero de notas."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Qual e a formula da escala menor natural?", opcoes: ["T ST T T ST T T", "T T ST T T T ST", "ST T T ST T T T", "T T T ST T ST T"], resposta: 0, explicacoes: ["Correto. T-ST-T-T-ST-T-T define o modo menor natural (eolio), com terca menor, sexta menor e setima menor.", "Incorreto. Essa e a formula da escala maior.", "Incorreto. A sequencia nao forma um modo diatonico valido.", "Incorreto. A distribuicao intervalar esta quebrada."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Uma triade tem quantas notas?", opcoes: ["2", "3", "4", "5"], resposta: 1, explicacoes: ["Incorreto. Duas notas formam apenas um intervalo.", "Correto. Triade e formada por empilhamento de tercas: fundamental, terca e quinta.", "Incorreto. Quatro notas formam tetrade.", "Incorreto. Cinco notas ja sao extensoes."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Triade maior possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 0, explicacoes: ["Correto. A terca maior (4 semitons) define o carater maior do acorde.", "Incorreto. Terca menor mudaria o acorde para menor.", "Incorreto. Quarta nao faz parte da estrutura basica.", "Incorreto. Segunda e extensao, nao base."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Triade menor possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 1, explicacoes: ["Incorreto. Terca maior caracteriza acorde maior.", "Correto. Terca menor (3 semitons) define o acorde menor.", "Incorreto. Quarta nao define triade.", "Incorreto. Segunda nao e estrutural."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "O V grau tem funcao:", opcoes: ["Tonica", "Dominante", "Subdominante", "Relativa"], resposta: 1, explicacoes: ["Incorreto. Tonica e repouso.", "Correto. O V grau contem o tritono e exerce funcao dominante, gerando forte tensao.", "Incorreto. Subdominante prepara, nao tensiona ao maximo.", "Incorreto. Relativa nao e funcao principal."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "O I grau tem funcao:", opcoes: ["Dominante", "Tonica", "Subdominante", "Sensivel"], resposta: 1, explicacoes: ["Incorreto. Dominante gera tensao.", "Correto. A tonica e o centro tonal e ponto de repouso.", "Incorreto. Subdominante prepara tensao.", "Incorreto. Sensivel e o VII grau."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Cadencia V-I e:", opcoes: ["Imperfeita", "Perfeita", "Plagal", "Deceptiva"], resposta: 1, explicacoes: ["Incorreto. A cadencia imperfeita ocorre quando nao ha sensacao plena de fechamento, geralmente quando a tonica aparece em inversao ou posicao fraca.", "Correto. A cadencia V-I e chamada de cadencia perfeita (ou autentica) porque representa a resolucao mais forte dentro do sistema tonal. Isso acontece porque o acorde dominante (V) contem o tritono (entre a terca e a setima do acorde), que gera tensao maxima e resolve diretamente na tonica (I), criando sensacao de conclusao completa.", "Incorreto. A cadencia plagal ocorre entre IV-I, conhecida como efeito 'amem', muito comum em musica sacra.", "Incorreto. A cadencia deceptiva ocorre quando o V nao resolve na tonica, mas sim em outro acorde, geralmente o VI."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Quantos semitons tem uma quinta justa?", opcoes: ["5", "6", "7", "8"], resposta: 2, explicacoes: ["Incorreto. 5 semitons e quarta justa.", "Incorreto. 6 semitons e tritono.", "Correto. Quinta justa possui 7 semitons.", "Incorreto. 8 semitons e sexta menor."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Quantos semitons tem uma terca maior?", opcoes: ["2", "3", "4", "5"], resposta: 2, explicacoes: ["Incorreto. 2 semitons e segunda maior.", "Incorreto. 3 semitons e terca menor.", "Correto. 4 semitons definem a terca maior.", "Incorreto. 5 semitons e quarta justa."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "O que e enarmonia?", opcoes: ["Mesmo som, nomes diferentes", "Notas diferentes", "Intervalos iguais", "Acordes iguais"], resposta: 0, explicacoes: ["Correto. Notas com mesmo som, mas grafia diferente (C# = Db).", "Incorreto. Notas diferentes nao sao enarmonicas.", "Incorreto. Intervalos iguais nao definem enarmonia.", "Incorreto. Acordes iguais nao sao o foco do conceito."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "O que e modulacao?", opcoes: ["Mudanca de ritmo", "Mudanca de tonalidade", "Mudanca de intensidade", "Mudanca de timbre"], resposta: 1, explicacoes: ["Incorreto. Ritmo nao altera tonalidade.", "Correto. Modulacao e mudanca de centro tonal dentro da musica.", "Incorreto. Intensidade nao muda tonalidade.", "Incorreto. Timbre nao altera funcao tonal."] },

  // HARMONIA FUNCIONAL — FACIL
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "O que e funcao harmonica?", opcoes: ["Funcao que define a intensidade da musica", "Funcao que define o papel do acorde na tonalidade", "Funcao que define a velocidade", "Funcao que define o timbre"], resposta: 1, explicacoes: ["Incorreto. Intensidade e dinamica.", "Correto. Define o papel do acorde na tonalidade (T, SD, D).", "Incorreto. Velocidade e andamento.", "Incorreto. Timbre e cor sonora."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Qual acorde representa a funcao tonica?", opcoes: ["IV grau", "V grau", "I grau", "II grau"], resposta: 2, explicacoes: ["Incorreto. IV e subdominante.", "Incorreto. V e dominante.", "Correto. I grau representa a tonica.", "Incorreto. II e subdominante."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Qual acorde representa a funcao dominante?", opcoes: ["I grau", "III grau", "V grau", "VI grau"], resposta: 2, explicacoes: ["Incorreto. I e tonica.", "Incorreto. III nao e dominante principal.", "Correto. V grau exerce funcao dominante.", "Incorreto. VI e relativa."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Qual acorde representa a funcao subdominante?", opcoes: ["IV grau", "I grau", "V grau", "VII grau"], resposta: 0, explicacoes: ["Correto. IV grau exerce funcao subdominante.", "Incorreto. I e tonica.", "Incorreto. V e dominante.", "Incorreto. VII e sensivel."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Qual funcao harmonica gera maior tensao?", opcoes: ["Subdominante", "Dominante", "Tonica", "Relativa"], resposta: 1, explicacoes: ["Incorreto. Subdominante prepara.", "Correto. Dominante gera tensao maxima.", "Incorreto. Tonica e repouso.", "Incorreto. Relativa nao gera tensao principal."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Na progressao C - F - G - C, qual acorde exerce funcao dominante?", opcoes: ["F", "Am", "G", "C"], resposta: 2, explicacoes: ["Incorreto. F e subdominante.", "Incorreto. Am nem aparece.", "Correto. G e V grau e cria tensao antes da resolucao.", "Incorreto. C e tonica."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "Na tonalidade de Do maior, qual e o acorde de tonica?", opcoes: ["F", "G", "C", "Dm"], resposta: 2, explicacoes: ["Incorreto. F e subdominante.", "Incorreto. G e dominante.", "Correto. C e a tonica de Do maior.", "Incorreto. Dm e subdominante."] },
  { nivel: "facil", topico: "harmonia-funcional", pergunta: "A progressao G - C representa:", opcoes: ["Subdominante para Dominante", "Dominante para Tonica", "Tonica para Dominante", "Tonica para Subdominante"], resposta: 1, explicacoes: ["Incorreto. Nao e SD-D.", "Correto. Dominante resolve na tonica.", "Incorreto. Nao comeca na tonica.", "Incorreto. Nao e T-SD."] },

  // HARMONIA FUNCIONAL — MEDIO
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Qual e a funcao do IV grau?", opcoes: ["Subdominante", "Tonica", "Dominante", "Sensivel"], resposta: 0, explicacoes: ["Correto. IV exerce funcao subdominante.", "Incorreto. Nao e tonica.", "Incorreto. Nao e dominante.", "Incorreto. Sensivel e VII."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Qual e a funcao do V grau?", opcoes: ["Dominante", "Subdominante", "Tonica", "Relativa"], resposta: 0, explicacoes: ["Correto. V grau exerce funcao dominante, gerando tensao.", "Incorreto. Subdominante e IV ou II.", "Incorreto. Tonica e I grau.", "Incorreto. Relativa nao e funcao principal."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Na progressao Dm - G - C, a sequencia funcional correta e:", opcoes: ["Tonica - Dominante - Tonica", "Subdominante - Dominante - Tonica", "Dominante - Tonica - Subdominante", "Tonica - Subdominante - Dominante"], resposta: 1, explicacoes: ["Incorreto. Dm nao e tonica.", "Correto. II (SD) -> V (D) -> I (T), progressao classica.", "Incorreto. Ordem funcional errada.", "Incorreto. Nao resolve corretamente."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Na progressao C - Am - Dm - G, o acorde Am exerce:", opcoes: ["Dominante", "Subdominante", "Tonica relativa", "Sensivel"], resposta: 2, explicacoes: ["Incorreto. Nao cria tensao.", "Incorreto. Nao e preparacao direta.", "Correto. VI grau funciona como tonica relativa.", "Incorreto. Sensivel e VII."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Qual cadencia esta presente em G - C?", opcoes: ["Plagal", "Perfeita", "Interrompida", "Modal"], resposta: 1, explicacoes: ["Incorreto. A cadencia plagal seria F-C (IV-I), nao G-C.", "Correto. G-C representa V-I na tonalidade de C maior, caracterizando uma cadencia perfeita. Aqui ocorre o movimento mais forte da harmonia tonal: tensao (dominante) -> resolucao (tonica).", "Incorreto. Cadencia interrompida (deceptiva) ocorre quando o V resolve no VI.", "Incorreto. Cadencia modal envolve linguagem fora do sistema tonal tradicional."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "A progressao I - IV - V - I representa:", opcoes: ["Progressao cromatica", "Progressao funcional basica", "Escala menor", "Modulacao"], resposta: 1, explicacoes: ["Incorreto. Nao e cromatica.", "Correto. E progressao funcional basica.", "Incorreto. Nao define escala.", "Incorreto. Nao ha mudanca de tonalidade."] },
  { nivel: "medio", topico: "harmonia-funcional", pergunta: "Qual acorde cria expectativa de resolucao?", opcoes: ["I grau", "III grau", "IV grau", "V grau"], resposta: 3, explicacoes: ["Incorreto. Tonica resolve.", "Incorreto. III e fraco funcionalmente.", "Incorreto. IV prepara.", "Correto. V contem tritono e sensivel, gerando maxima tensao."] },

  // HARMONIA FUNCIONAL — DIFICIL
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Na progressao C - Am - Dm - G - C, qual e a sequencia funcional correta?", opcoes: ["T - Trel - SD - D - T", "T - SD - D - T - SD", "SD - D - T - SD - D", "T - D - SD - T - D"], resposta: 0, explicacoes: ["Correto. T - Trel - SD - D - T representa um ciclo tonal completo. A musica parte do repouso (tonica), passa por uma area de variacao (tonica relativa), prepara a tensao (subdominante), cria tensao (dominante) e resolve novamente na tonica.", "Incorreto. A sequencia perde logica funcional, pois desloca funcoes essenciais.", "Incorreto. Comecar em subdominante quebra a sensacao de centro tonal.", "Incorreto. A ordem dominante-subdominante esta invertida, o que compromete a logica da resolucao."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Na progressao Dm - G - C - Am, o acorde Am funciona como:", opcoes: ["Dominante", "Tonica relativa", "Subdominante", "Sensivel"], resposta: 1, explicacoes: ["Incorreto. Nao e dominante.", "Correto. Am e tonica relativa (VI grau).", "Incorreto. Nao e subdominante.", "Incorreto. Nao e sensivel."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Qual progressao representa uma cadencia plagal?", opcoes: ["G - C", "Dm - G", "F - C", "Am - Dm"], resposta: 2, explicacoes: ["Incorreto. G-C e V-I (cadencia perfeita).", "Incorreto. Dm-G e uma preparacao para dominante (II-V).", "Correto. F-C representa IV-I, que caracteriza a cadencia plagal. Diferente da cadencia perfeita, ela nao tem o tritono dominante, portanto gera uma resolucao mais suave, muito associada ao final de hinos e musicas religiosas.", "Incorreto. Am-Dm nao resolve na tonica, portanto nao forma cadencia conclusiva."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Na progressao G - Am, ocorre:", opcoes: ["Cadencia perfeita", "Resolucao plagal", "Cadencia deceptiva", "Modulacao direta"], resposta: 2, explicacoes: ["Incorreto. A cadencia perfeita exige resolucao V-I, o que nao acontece aqui.", "Incorreto. A cadencia plagal seria IV-I.", "Correto. Aqui temos uma cadencia deceptiva (V-VI). O acorde dominante (G) cria expectativa de resolucao na tonica (C), mas em vez disso resolve em Am (VI grau). Isso engana o ouvido e prolonga a progressao, sendo muito usada para evitar fechamento imediato.", "Incorreto. Nao ha mudanca de tonalidade, apenas uma resolucao inesperada dentro da mesma tonalidade."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Qual analise correta para Dm - G - C?", opcoes: ["I - IV - V", "II - V - I", "III - VI - II", "V - I - IV"], resposta: 1, explicacoes: ["Incorreto. Nao comeca em I.", "Correto. II - V - I e progressao padrao.", "Incorreto. Sequencia errada.", "Incorreto. Ordem incorreta."] },
  { nivel: "dificil", topico: "harmonia-funcional", pergunta: "Qual grau geralmente exerce funcao dominante secundaria?", opcoes: ["V/V", "I", "IV", "VI"], resposta: 0, explicacoes: ["Correto. V/V e o dominante da dominante.", "Incorreto. I nao cria tensao.", "Incorreto. IV e subdominante.", "Incorreto. VI e relativa."] },

  // HISTORIA DA MUSICA — FACIL
  { nivel: "facil", topico: "historia-da-musica", pergunta: "A musica na Idade Media ficou conhecida por: [REVISAR]", opcoes: ["Desenvolvimento da polifonia", "Uso exclusivo de instrumentos eletricos", "Apenas canto solo", "Ausencia de organizacao musical"], resposta: 0 },
  { nivel: "facil", topico: "historia-da-musica", pergunta: "Quem foi [REVISAR - inserir nome]? (Compositor da Idade Media ligado a polifonia)", opcoes: ["Compositor da Idade Media ligado a polifonia", "Compositor do periodo classico", "Musico do jazz moderno", "Cantor popular contemporaneo"], resposta: 0 },
  { nivel: "facil", topico: "historia-da-musica", pergunta: "Quem foi [REVISAR - inserir nome]? (Compositor medieval que desenvolveu a polifonia)", opcoes: ["Compositor barroco", "Compositor medieval que desenvolveu a polifonia", "Compositor romantico", "Teorico moderno"], resposta: 1 },
  { nivel: "facil", topico: "historia-da-musica", pergunta: "O que e organum?", opcoes: ["Forma inicial de polifonia", "Instrumento de corda", "Ritmo moderno", "Escala musical"], resposta: 0 },

  // HISTORIA DA MUSICA — MEDIO
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Qual compositor esta associado a obra 'O Cravo Bem Temperado'?", opcoes: ["Mozart", "Bach", "Beethoven", "Chopin"], resposta: 1 },
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Qual compositor e conhecido pela opera 'A Flauta Magica'?", opcoes: ["Verdi", "Mozart", "Puccini", "Wagner"], resposta: 1 },
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Qual compositor e associado ao periodo Romantico?", opcoes: ["Bach", "Mozart", "Chopin", "Palestrina"], resposta: 2 },
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Qual forma musical era comum na Idade Media?", opcoes: ["Sinfonia", "Moteto", "Sonata", "Concerto"], resposta: 1 },

  // HISTORIA DA MUSICA — DIFICIL
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "A Escola de Notre-Dame contribuiu principalmente para:", opcoes: ["Desenvolvimento da musica eletronica", "Evolucao da polifonia organizada", "Criacao da sinfonia", "Desenvolvimento do jazz"], resposta: 1 },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "Qual inovacao esta ligada a [REVISAR - inserir nome]?", opcoes: ["Uso de acordes modernos", "Ampliacao da polifonia para multiplas vozes", "Criacao da tonalidade maior", "Uso de instrumentos eletricos"], resposta: 1 },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "O moteto medieval se caracteriza por:", opcoes: ["Uso de uma unica voz", "Uso de varias vozes com textos diferentes", "Apenas instrumentos", "Ausencia de ritmo"], resposta: 1 },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "Qual compositor esta associado ao impressionismo musical?", opcoes: ["Bach", "Beethoven", "Debussy", "Mozart"], resposta: 2 },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "Qual caracteristica define o periodo Barroco?", opcoes: ["Uso de polifonia complexa e baixo continuo", "Ausencia de harmonia", "Uso apenas de voz solo", "Musica sem estrutura"], resposta: 0 },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "Qual obra e um exemplo de fuga barroca?", opcoes: ["Sinfonia no 5", "O Cravo Bem Temperado", "Clair de Lune", "Ave Maria moderna"], resposta: 1 },

  // HISTORIA DA MUSICA COM EXPLICACOES (FEEDBACK DETALHADO)
  { nivel: "facil", topico: "historia-da-musica", pergunta: "Em qual periodo surgiu o canto gregoriano?", opcoes: ["Renascimento", "Idade Media", "Barroco", "Classico"], resposta: 1, explicacoes: ["Incorreto. Veio depois.", "Correto. Musica medieval religiosa.", "Incorreto. Posterior.", "Incorreto. Posterior."] },
  { nivel: "facil", topico: "historia-da-musica", pergunta: "A musica na Catedral de Notre-Dame ficou conhecida por:", opcoes: ["Polifonia", "Musica eletronica", "Monodia moderna", "Ausencia de estrutura"], resposta: 0, explicacoes: ["Correto. Desenvolvimento da polifonia.", "Incorreto. Seculo XX.", "Incorreto. Nao corresponde.", "Incorreto. Musica organizada."] },
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Quem compos a 9a Sinfonia?", opcoes: ["Bach", "Mozart", "Beethoven", "Debussy"], resposta: 2, explicacoes: ["Incorreto. Barroco.", "Incorreto. Nao foi ele.", "Correto. Beethoven.", "Incorreto. Impressionismo."] },
  { nivel: "medio", topico: "historia-da-musica", pergunta: "Qual compositor pertence ao Renascimento?", opcoes: ["Bach", "Palestrina", "Beethoven", "Debussy"], resposta: 1, explicacoes: ["Incorreto. Barroco.", "Correto. Renascimento.", "Incorreto. Classico/Romantico.", "Incorreto. Moderno."] },
  { nivel: "dificil", topico: "historia-da-musica", pergunta: "A Escola de Notre-Dame contribuiu para:", opcoes: ["Musica eletronica", "Evolucao da polifonia", "Sinfonia", "Jazz"], resposta: 1, explicacoes: ["Incorreto. Seculo XX.", "Correto. Polifonia organizada.", "Incorreto. Periodo classico.", "Incorreto. Seculo XX."] },
];

const harmonia_medio = [
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "campo_harmonico",
    pergunta: "Na tonalidade de C maior, qual é o acorde do II grau (supertônica)?",
    opcoes: ["Dm", "Em", "F", "G"],
    resposta: 0,
    explicacoes: [
      "Correto. Dm é o II grau.",
      "Incorreto. Em é III grau.",
      "Incorreto. F é IV grau.",
      "Incorreto. G é V grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "campo_harmonico",
    pergunta: "Na tonalidade de G maior, qual é o acorde do VI grau?",
    opcoes: ["Em", "Bm", "Am", "C"],
    resposta: 0,
    explicacoes: [
      "Correto. Em é VI grau.",
      "Incorreto. Bm é III.",
      "Incorreto. Am é II.",
      "Incorreto. C é IV.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "funcao",
    pergunta: "Na tonalidade de C maior, qual função exerce o acorde F (IV grau)?",
    opcoes: ["Tônica", "Dominante", "Subdominante", "Sensível"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto. IV grau é subdominante.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "funcao",
    pergunta: "Na tonalidade de D maior, qual acorde exerce função dominante (V grau)?",
    opcoes: ["G", "A", "D", "Bm"],
    resposta: 1,
    explicacoes: ["Incorreto. IV grau.", "Correto. A é V grau.", "Incorreto. I grau.", "Incorreto. VI grau."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "progressao",
    pergunta: "Na tonalidade de C maior, a progressão Dm → G → C representa:",
    opcoes: ["I - IV - V", "II - V - I", "V - I - IV", "III - VI - II"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. II-V-I é progressão fundamental.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na progressão C → Am → Dm → G, o acorde Am exerce qual função?",
    opcoes: ["Dominante", "Subdominante", "Tônica relativa", "Sensível"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto. VI grau funciona como tônica relativa.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de G maior, qual acorde exerce função subdominante (IV grau)?",
    opcoes: ["D", "C", "G", "Em"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. C é IV grau.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "inversao",
    pergunta: "Um acorde em primeira inversão possui qual nota no baixo?",
    opcoes: ["Fundamental", "Terça", "Quinta", "Sétima"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Terça no baixo.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "inversao",
    pergunta: "Um acorde em segunda inversão possui qual nota no baixo?",
    opcoes: ["Terça", "Quinta", "Fundamental", "Sétima"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Quinta no baixo.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "Na tonalidade de C maior, a sequência F → G → C representa:",
    opcoes: ["Cadência plagal", "Cadência autêntica completa", "Cadência deceptiva", "Cadência modal"],
    resposta: 1,
    explicacoes: ["Incorreto. IV-I.", "Correto. IV-V-I.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "relativa",
    pergunta: "Na tonalidade de C maior, qual acorde é a relativa menor (VI grau)?",
    opcoes: ["Am", "Dm", "Em", "G"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de D maior, qual acorde é o II grau (supertônica)?",
    opcoes: ["Em", "F#m", "G", "A"],
    resposta: 0,
    explicacoes: ["Correto. Em é II grau.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de G maior, qual acorde é o V grau (dominante)?",
    opcoes: ["D", "C", "G", "Em"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de C maior, qual acorde é o III grau?",
    opcoes: ["Em", "Dm", "F", "Am"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de G maior, qual acorde é o IV grau?",
    opcoes: ["C", "D", "G", "Am"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de D maior, qual acorde é o V grau?",
    opcoes: ["A", "G", "D", "Bm"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de C maior, qual acorde exerce função dominante?",
    opcoes: ["G", "F", "C", "Am"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de G maior, qual acorde é o VI grau?",
    opcoes: ["Em", "Bm", "Am", "C"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de D maior, qual acorde é o IV grau?",
    opcoes: ["G", "A", "D", "Em"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de C maior, qual acorde é o V grau?",
    opcoes: ["G", "F", "C", "Am"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
];

perguntas.push(
  ...harmonia_medio.map((q) => ({
    nivel: q.nivel,
    tema: q.tema,
    subtema: q.subtema,
    topico: "harmonia-funcional",
    pergunta: q.pergunta,
    opcoes: q.opcoes,
    resposta: q.resposta,
    explicacoes: q.explicacoes,
  }))
);

const harmonia_dificil = [
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "Na tonalidade de C maior, a sequência G → Am (V → VI) representa qual tipo de cadência?",
    opcoes: ["Perfeita", "Plagal", "Deceptiva", "Autêntica"],
    resposta: 2,
    explicacoes: [
      "Incorreto. V-I.",
      "Incorreto. IV-I.",
      "Correto. V resolve no VI, criando efeito de surpresa.",
      "Incorreto.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    pergunta: "Na tonalidade de C maior, o acorde G é o V grau. Qual acorde é o dominante desse acorde (V de G)?",
    opcoes: ["D", "A", "E", "B"],
    resposta: 0,
    explicacoes: ["Correto. D é dominante de G.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    pergunta: "Na tonalidade de G maior, o acorde Am é o II grau. Qual acorde é o dominante de Am?",
    opcoes: ["E", "A", "D", "B"],
    resposta: 0,
    explicacoes: ["Correto. E é dominante de Am.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    pergunta: "Na tonalidade de C maior, o acorde Am é o VI grau. Qual acorde funciona como dominante de Am?",
    opcoes: ["E", "G", "D", "A"],
    resposta: 0,
    explicacoes: ["Correto. E é dominante de Am.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    pergunta: "Na tonalidade de C maior, o acorde Dm é o II grau. Qual acorde é o dominante de Dm?",
    opcoes: ["A", "E", "G", "B"],
    resposta: 0,
    explicacoes: ["Correto. A é dominante de Dm.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "emprestimo_modal",
    pergunta: "Na tonalidade de C maior, o acorde Bb não pertence ao campo harmônico. De onde ele vem?",
    opcoes: ["Dominante secundária", "Empréstimo modal", "Modulação", "Função tônica"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Vem do modo menor paralelo.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "emprestimo_modal",
    pergunta: "Na tonalidade de C maior, o acorde Ab é usado ocasionalmente. Isso caracteriza:",
    opcoes: ["Modulação", "Empréstimo modal", "Dominante", "Cadência"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Acorde emprestado do modo menor.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "modulacao",
    pergunta: "Quando uma música em C maior passa a ter G como novo centro tonal, isso é chamado de:",
    opcoes: ["Cadência", "Modulação", "Inversão", "Função"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Mudança de tonalidade.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na progressão C → E7 → Am, o acorde E7 exerce qual função?",
    opcoes: ["Tônica", "Subdominante", "Dominante do Am", "Empréstimo modal"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto. E7 é dominante de Am.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de G maior, o acorde Em é o VI grau. Qual acorde é o dominante de Em?",
    opcoes: ["B", "E", "A", "D"],
    resposta: 0,
    explicacoes: ["Correto. B é dominante de Em.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de D maior, o acorde A é o V grau. Qual acorde é dominante de A?",
    opcoes: ["E", "B", "F#", "C#"],
    resposta: 0,
    explicacoes: ["Correto. E é dominante de A.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    pergunta: "Na tonalidade de C maior, o acorde Em é o III grau. Qual acorde é dominante de Em?",
    opcoes: ["B", "E", "A", "D"],
    resposta: 0,
    explicacoes: ["Correto. B é dominante de Em.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "acordes",
    pergunta: "Um acorde diminuto é formado por quais intervalos?",
    opcoes: [
      "terça maior + quinta justa",
      "terça menor + quinta diminuta",
      "terça maior + quinta aumentada",
      "terça menor + quinta justa",
    ],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. Estrutura do diminuto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "acordes",
    pergunta: "Um acorde aumentado possui qual característica principal?",
    opcoes: ["quinta aumentada", "quinta diminuta", "terça menor", "sétima menor"],
    resposta: 0,
    explicacoes: ["Correto.", "Incorreto.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "Na tonalidade de C maior, a sequência F → C representa:",
    opcoes: ["Perfeita", "Plagal", "Deceptiva", "Autêntica"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. IV-I.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "Na tonalidade de C maior, a sequência G → C representa:",
    opcoes: ["Plagal", "Perfeita", "Deceptiva", "Modal"],
    resposta: 1,
    explicacoes: ["Incorreto.", "Correto. V-I.", "Incorreto.", "Incorreto."],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "Na tonalidade de C maior, a sequência G → Am representa:",
    opcoes: ["Perfeita", "Plagal", "Deceptiva", "Autêntica"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto.", "Incorreto."],
  },
];

perguntas.push(
  ...harmonia_dificil.map((q) => ({
    nivel: q.nivel,
    tema: q.tema,
    subtema: q.subtema,
    topico: "harmonia-funcional",
    pergunta: q.pergunta,
    opcoes: q.opcoes,
    resposta: q.resposta,
    explicacoes: q.explicacoes,
  }))
);

const harmonia_facil = [
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "funcao",
    pergunta: "Qual função harmônica representa estabilidade?",
    opcoes: ["Dominante", "Subdominante", "Tônica", "Sensível"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Dominante gera tensão.",
      "Incorreto. Subdominante prepara.",
      "Correto. A tônica é o ponto de repouso.",
      "Incorreto. Sensível cria expectativa.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "dominante",
    pergunta: "Qual função cria tensão que resolve na tônica?",
    opcoes: ["Tônica", "Dominante", "Subdominante", "Relativa"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Representa repouso.",
      "Correto. A dominante cria tensão e pede resolução.",
      "Incorreto. Apenas prepara.",
      "Incorreto. Não é função principal.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "graus",
    pergunta: "Qual grau representa a tônica?",
    opcoes: ["V", "IV", "I", "II"],
    resposta: 2,
    explicacoes: [
      "Incorreto. V é dominante.",
      "Incorreto. IV é subdominante.",
      "Correto. I é tônica.",
      "Incorreto. II é preparação.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "graus",
    pergunta: "Qual grau representa a dominante?",
    opcoes: ["I", "III", "V", "VI"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Tônica.",
      "Incorreto. Não exerce função principal.",
      "Correto. V é dominante.",
      "Incorreto. Relativa.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "subdominante",
    pergunta: "Qual função prepara a dominante?",
    opcoes: ["Tônica", "Dominante", "Subdominante", "Sensível"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Repouso.",
      "Incorreto. Já é tensão.",
      "Correto. Subdominante prepara a tensão.",
      "Incorreto.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "O que é cadência perfeita?",
    opcoes: ["IV → I", "V → I", "V → VI", "I → IV"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Plagal.",
      "Correto. Dominante resolve na tônica.",
      "Incorreto. Deceptiva.",
      "Incorreto.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "O que é cadência plagal?",
    opcoes: ["IV → I", "V → I", "V → VI", "II → V"],
    resposta: 0,
    explicacoes: [
      "Correto. Subdominante para tônica.",
      "Incorreto. Perfeita.",
      "Incorreto.",
      "Incorreto.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "cadencia",
    pergunta: "O que é cadência deceptiva?",
    opcoes: ["V → I", "IV → I", "V → VI", "I → V"],
    resposta: 2,
    explicacoes: [
      "Incorreto.",
      "Incorreto.",
      "Correto. Evita resolução esperada.",
      "Incorreto.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "campo_harmonico",
    pergunta: "Quantos graus tem o campo harmônico maior?",
    opcoes: ["5", "6", "7", "8"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto. São 7 graus.", "Incorreto."],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "relativa",
    pergunta: "Qual é a relativa menor de C?",
    opcoes: ["Em", "Dm", "Am", "G"],
    resposta: 2,
    explicacoes: ["Incorreto.", "Incorreto.", "Correto. Am é relativa.", "Incorreto."],
  },
];

perguntas.push(
  ...harmonia_facil.map((q) => ({
    nivel: q.nivel,
    tema: q.tema,
    subtema: q.subtema,
    topico: "harmonia-funcional",
    pergunta: q.pergunta,
    opcoes: q.opcoes,
    resposta: q.resposta,
    explicacoes: q.explicacoes,
  }))
);

const harmonia_extra = [
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "funcao",
    topico: "harmonia-funcional",
    pergunta: "Em uma tonalidade maior, qual grau costuma iniciar o senso de repouso?",
    opcoes: ["V", "II", "I", "VII"],
    resposta: 2,
    explicacoes: [
      "Incorreto. V cria tensao e pede resolucao.",
      "Incorreto. II geralmente prepara a dominante.",
      "Correto. I grau (tonica) e o principal ponto de estabilidade.",
      "Incorreto. VII e sensivel, com tendencia de movimento para a tonica.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de C maior, qual acorde corresponde ao IV grau?",
    opcoes: ["Dm", "F", "G", "Am"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Dm e II grau.",
      "Correto. F e o IV grau em C maior.",
      "Incorreto. G e V grau.",
      "Incorreto. Am e VI grau.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Qual sequencia representa uma cadencia que evita o fechamento esperado?",
    opcoes: ["V - I", "IV - I", "V - VI", "II - V"],
    resposta: 2,
    explicacoes: [
      "Incorreto. V-I e cadencia perfeita, com fechamento forte.",
      "Incorreto. IV-I e cadencia plagal.",
      "Correto. V-VI caracteriza cadencia deceptiva, adiando a resolucao final.",
      "Incorreto. II-V prepara uma resolucao, mas nao fecha por si so.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de G maior, qual e o acorde do III grau?",
    opcoes: ["Bm", "Am", "C", "D"],
    resposta: 0,
    explicacoes: [
      "Correto. Bm e o III grau no campo harmonico de G maior.",
      "Incorreto. Am e II grau.",
      "Incorreto. C e IV grau.",
      "Incorreto. D e V grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Na progressao F - G - Em - Am (em C maior), qual funcao exerce o acorde G?",
    opcoes: ["Tonica", "Dominante", "Subdominante", "Relativa"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Tonica e o I grau (C).",
      "Correto. G e o V grau e exerce funcao dominante.",
      "Incorreto. Subdominante e mais associada a IV ou II.",
      "Incorreto. Relativa nao e uma funcao principal nesse contexto.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "inversao",
    topico: "harmonia-funcional",
    pergunta: "Um acorde em estado fundamental possui qual nota no baixo?",
    opcoes: ["Terca", "Quinta", "Setima", "Fundamental"],
    resposta: 3,
    explicacoes: [
      "Incorreto. Terca no baixo caracteriza primeira inversao.",
      "Incorreto. Quinta no baixo caracteriza segunda inversao.",
      "Incorreto. Setima no baixo aparece em inversoes de acordes de setima.",
      "Correto. Em estado fundamental, a fundamental fica no baixo.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, qual leitura funcional de Dm - G - C esta correta?",
    opcoes: ["II - V - I", "IV - V - I", "VI - II - V", "I - IV - V"],
    resposta: 0,
    explicacoes: [
      "Correto. Dm e II, G e V, C e I.",
      "Incorreto. Dm nao e IV em C maior.",
      "Incorreto. A sequencia proposta nao corresponde aos acordes dados.",
      "Incorreto. C nao aparece na posicao inicial dessa leitura.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de C maior, qual acorde funciona como V/II?",
    opcoes: ["E", "A", "D", "B"],
    resposta: 1,
    explicacoes: [
      "Incorreto. E e dominante de Am (VI).",
      "Correto. A (ou A7) funciona como dominante de Dm, que e o II grau.",
      "Incorreto. D e dominante de G (V), ou seja, V/V.",
      "Incorreto. B e dominante de Em (III).",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Na progressao C - E7 - Am - Dm - G - C, o acorde E7 e melhor descrito como:",
    opcoes: ["Subdominante diatonica", "Dominante secundaria do VI", "Emprestimo modal do paralelo maior", "Acorde diminuto de passagem"],
    resposta: 1,
    explicacoes: [
      "Incorreto. E7 nao e subdominante em C maior.",
      "Correto. E7 aponta para Am, atuando como dominante secundaria (V/VI).",
      "Incorreto. Nao se trata de emprestimo modal nesse caso.",
      "Incorreto. E7 e acorde dominante, nao diminuto.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "emprestimo_modal",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, o uso de Ab maior geralmente indica:",
    opcoes: ["Cadencia perfeita", "Dominante secundaria", "Emprestimo modal de C menor", "Modulacao obrigatoria para Ab maior"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Cadencia perfeita e tipicamente V-I.",
      "Incorreto. Ab nao exerce papel dominante tipico em C maior.",
      "Correto. Ab pode ser emprestado do modo menor paralelo (C menor).",
      "Incorreto. O acorde pode aparecer sem modulacao completa.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "acordes",
    topico: "harmonia-funcional",
    pergunta: "Qual intervalo transforma uma triade maior em aumentada?",
    opcoes: ["Elevar a terca em 1 semitom", "Elevar a quinta em 1 semitom", "Rebaixar a terca em 1 semitom", "Rebaixar a quinta em 1 semitom"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Alterar a terca muda o modo maior/menor do acorde.",
      "Correto. A triade aumentada possui quinta aumentada em relacao a triade maior.",
      "Incorreto. Isso transformaria o acorde em menor.",
      "Incorreto. Rebaixar a quinta levaria a uma quinta diminuta.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, qual progressao tende a produzir maior sensacao de conclusao final?",
    opcoes: ["IV - I", "V - VI", "II - V", "V - I"],
    resposta: 3,
    explicacoes: [
      "Incorreto. IV-I e conclusiva, mas mais suave (plagal).",
      "Incorreto. V-VI e deceptiva, adia o fechamento.",
      "Incorreto. II-V prepara resolucao, mas nao conclui sozinho.",
      "Correto. V-I realiza a resolucao tonal mais forte (cadencia perfeita).",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "funcao",
    topico: "harmonia-funcional",
    pergunta: "Qual funcao harmonica costuma representar preparacao antes da dominante?",
    opcoes: ["Tonica", "Subdominante", "Sensivel", "Relativa"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Tonica representa repouso.",
      "Correto. Subdominante prepara o caminho para a dominante.",
      "Incorreto. Sensivel e um grau, nao uma funcao principal isolada.",
      "Incorreto. Relativa nao substitui a funcao subdominante nesse papel.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "A sequencia IV - I recebe qual nome?",
    opcoes: ["Cadencia perfeita", "Cadencia plagal", "Cadencia deceptiva", "Cadencia interrompida"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Cadencia perfeita e V-I.",
      "Correto. IV-I define a cadencia plagal.",
      "Incorreto. Deceptiva ocorre em V-VI.",
      "Incorreto. Interrompida e outro nome usado para a deceptiva.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de C maior, qual acorde e o VI grau?",
    opcoes: ["Em", "Am", "Dm", "G"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Em e III grau.",
      "Correto. Am e o VI grau em C maior.",
      "Incorreto. Dm e II grau.",
      "Incorreto. G e V grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Na progressao Am - Dm - G - C (em C maior), qual e a leitura funcional mais adequada?",
    opcoes: ["Trel - SD - D - T", "T - SD - D - T", "SD - D - T - SD", "D - T - SD - D"],
    resposta: 0,
    explicacoes: [
      "Correto. Am atua como tonica relativa, seguido por SD, D e resolucao em T.",
      "Incorreto. Am nao e tonica principal em C maior.",
      "Incorreto. A ordem funcional apresentada nao corresponde a progressao.",
      "Incorreto. A progressao nao inicia em dominante.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de D maior, qual e o acorde do VI grau?",
    opcoes: ["Bm", "F#m", "Em", "G"],
    resposta: 0,
    explicacoes: [
      "Correto. Bm e o VI grau em D maior.",
      "Incorreto. F#m e III grau.",
      "Incorreto. Em e II grau.",
      "Incorreto. G e IV grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "inversao",
    topico: "harmonia-funcional",
    pergunta: "Em uma triade, quando a quinta esta no baixo, temos:",
    opcoes: ["Estado fundamental", "Primeira inversao", "Segunda inversao", "Acorde sus4"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Estado fundamental tem a fundamental no baixo.",
      "Incorreto. Primeira inversao tem a terca no baixo.",
      "Correto. Quinta no baixo caracteriza segunda inversao.",
      "Incorreto. Sus4 e outra estrutura intervalar.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, qual progressao exemplifica melhor uma preparacao cadencial sem resolucao final?",
    opcoes: ["II - V", "V - I", "IV - I", "V - VI"],
    resposta: 0,
    explicacoes: [
      "Correto. II-V prepara fortemente a resolucao, mas sem o I nao fecha plenamente.",
      "Incorreto. V-I ja representa fechamento tonal.",
      "Incorreto. IV-I tambem traz sensacao conclusiva (plagal).",
      "Incorreto. V-VI e deceptiva, nao apenas preparacao.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de C maior, o acorde D7 e normalmente analisado como:",
    opcoes: ["V/IV", "V/V", "II7 diatonico", "SubV de I"],
    resposta: 1,
    explicacoes: [
      "Incorreto. V/IV seria dominante de F (C7).",
      "Correto. D7 funciona como dominante de G, portanto V/V.",
      "Incorreto. Em C maior, o II diatonico e Dm7, nao D7.",
      "Incorreto. SubV de I seria Db7 em linguagem de substituicao tritonal.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Na progressao C - A7 - Dm - G - C, a funcao de A7 e:",
    opcoes: ["Dominante secundaria do II", "Emprestimo modal", "Tonica relativa", "Subdominante menor"],
    resposta: 0,
    explicacoes: [
      "Correto. A7 aponta para Dm, atuando como V/II.",
      "Incorreto. O comportamento principal aqui e de dominante secundaria.",
      "Incorreto. A7 nao exerce papel de tonica relativa.",
      "Incorreto. Nao e classificado como subdominante menor nesse contexto.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "emprestimo_modal",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, o acorde Bb em C - Bb - F sugere principalmente:",
    opcoes: ["Modulacao imediata para Bb maior", "Emprestimo modal do modo menor paralelo", "Dominante secundaria de G", "Acorde de passagem cromatica sem funcao"],
    resposta: 1,
    explicacoes: [
      "Incorreto. O uso isolado de Bb nao obriga modulacao completa.",
      "Correto. Bb e tipico de emprestimo modal de C menor.",
      "Incorreto. Dominante secundaria de G seria D ou D7.",
      "Incorreto. Embora possa ter cromatismo, ha funcao contextual clara no emprestimo modal.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Qual descricao define melhor a forca da cadencia autentica perfeita?",
    opcoes: ["Resolucao fraca por ausencia de dominante", "Movimento IV-I com fechamento liturgico", "Resolucao V-I com maior tensao e relaxamento tonal", "Troca de centro tonal sem relacao funcional"],
    resposta: 2,
    explicacoes: [
      "Incorreto. A cadencia autentica depende da dominante.",
      "Incorreto. Essa descricao corresponde a cadencia plagal.",
      "Correto. V-I concentra tensao dominante e resolucao completa na tonica.",
      "Incorreto. Isso descreve modulacao, nao cadencia autentica.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, a progressao C - F - Dm - G - C pode ser lida, respectivamente, como:",
    opcoes: ["T - SD - SD - D - T", "T - D - SD - D - T", "T - Trel - SD - D - T", "SD - T - D - SD - T"],
    resposta: 0,
    explicacoes: [
      "Correto. C (T), F (SD), Dm (SD), G (D), C (T) compoem um percurso funcional coerente.",
      "Incorreto. F nao exerce funcao dominante nesse contexto tonal.",
      "Incorreto. Nao ha tonica relativa nessa sequencia especifica.",
      "Incorreto. A progressao nao inicia em subdominante.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "dominante_secundaria",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de G maior, qual acorde representa V/VI?",
    opcoes: ["B", "C#", "D", "E"],
    resposta: 0,
    explicacoes: [
      "Correto. VI em G maior e Em; o dominante de Em e B (ou B7).",
      "Incorreto. C# nao cumpre a funcao dominante de Em nesse caso.",
      "Incorreto. D e V de G, nao V/VI.",
      "Incorreto. E e o proprio centro de chegada, nao seu dominante.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Qual alternativa descreve corretamente a diferenca entre cadencia perfeita e cadencia plagal?",
    opcoes: [
      "Perfeita e IV-I; plagal e V-I",
      "Perfeita tende a maior tensao-resolucao; plagal tende a resolucao mais suave",
      "Perfeita ocorre apenas no modo menor; plagal apenas no maior",
      "Nao ha diferenca funcional entre elas"
    ],
    resposta: 1,
    explicacoes: [
      "Incorreto. A relacao esta invertida.",
      "Correto. V-I tende ao fechamento mais forte; IV-I produz conclusao mais branda.",
      "Incorreto. Ambas podem ocorrer em diferentes contextos tonais.",
      "Incorreto. Ha diferenca clara de funcao e percepcao cadencial.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "acordes",
    topico: "harmonia-funcional",
    pergunta: "Uma tetrade dominante (X7) e caracterizada por:",
    opcoes: [
      "Terca menor e setima maior",
      "Terca maior e setima menor",
      "Terca menor e quinta aumentada",
      "Terca maior e setima maior"
    ],
    resposta: 1,
    explicacoes: [
      "Incorreto. Essa combinacao nao define o acorde dominante tradicional.",
      "Correto. A estrutura de dominante 7 contem terca maior e setima menor.",
      "Incorreto. Essa descricao nao corresponde ao modelo de dominante 7 funcional.",
      "Incorreto. Terca maior e setima maior definem acorde maior com setima maior.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "modulacao",
    topico: "harmonia-funcional",
    pergunta: "Em analise tonal, o principal indicio de modulacao consolidada e:",
    opcoes: [
      "Uso de um unico acorde cromatico isolado",
      "Aparicao de dominante e tonica confirmando novo centro",
      "Presenca obrigatoria de cadencia plagal",
      "Mudanca de andamento"
    ],
    resposta: 1,
    explicacoes: [
      "Incorreto. Um acorde cromatico sozinho pode ser apenas coloracao local.",
      "Correto. A confirmacao do novo centro geralmente envolve funcao dominante-tonica da nova tonalidade.",
      "Incorreto. Plagal nao e requisito para consolidar modulacao.",
      "Incorreto. Andamento e parametro temporal, nao prova de modulacao tonal.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "emprestimo_modal",
    topico: "harmonia-funcional",
    pergunta: "No contexto de C maior, o acorde Eb maior e melhor interpretado como:",
    opcoes: [
      "Acorde diatonico do campo maior",
      "Emprestimo modal do paralelo menor",
      "Dominante secundaria de Am",
      "Substituicao tritonal de G7"
    ],
    resposta: 1,
    explicacoes: [
      "Incorreto. Eb nao pertence ao campo harmonico diatonico de C maior.",
      "Correto. Eb pode ser explicado como emprestimo do modo menor paralelo.",
      "Incorreto. Dominante de Am seria E (ou E7).",
      "Incorreto. Substituicao tritonal de G7 seria Db7.",
    ],
  },
  {
    nivel: "dificil",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Em C maior, qual leitura funcional melhor descreve a progressao C - Am - F - G?",
    opcoes: ["T - Trel - SD - D", "T - SD - Trel - D", "SD - T - D - T", "T - D - SD - T"],
    resposta: 0,
    explicacoes: [
      "Correto. C (T), Am (Trel), F (SD), G (D) formam encadeamento funcional classico.",
      "Incorreto. Am nao desempenha papel de subdominante nesse contexto.",
      "Incorreto. A progressao nao inicia em subdominante.",
      "Incorreto. G nao aparece em posicao final de resolucao para tonica nessa sequencia.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "analise",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de A maior, qual acorde exerce funcao dominante?",
    opcoes: ["D", "E", "F#m", "C#m"],
    resposta: 1,
    explicacoes: [
      "Incorreto. D e IV grau (subdominante).",
      "Correto. E e V grau em A maior, com funcao dominante.",
      "Incorreto. F#m e VI grau.",
      "Incorreto. C#m e III grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Em G maior, qual acorde corresponde ao VII grau diatonico?",
    opcoes: ["F#m", "A", "F#dim", "Em"],
    resposta: 2,
    explicacoes: [
      "Incorreto. F#m e acorde do VII em campo menor harmonico, nao no maior diatonico.",
      "Incorreto. A e II grau em G maior.",
      "Correto. No campo maior, o VII grau forma acorde diminuto (F#dim).",
      "Incorreto. Em e VI grau.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "inversao",
    topico: "harmonia-funcional",
    pergunta: "No cifrado de inversoes de triades, I6 geralmente indica:",
    opcoes: ["Estado fundamental", "Primeira inversao", "Segunda inversao", "Acorde com setima"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Estado fundamental nao recebe 6.",
      "Correto. O numero 6 indica primeira inversao da triade.",
      "Incorreto. Segunda inversao e normalmente indicada por 6/4.",
      "Incorreto. Setima exige outras indicacoes intervalares.",
    ],
  },
  {
    nivel: "medio",
    tema: "harmonia",
    subtema: "cadencia",
    topico: "harmonia-funcional",
    pergunta: "Qual sequencia melhor representa uma semicadencia em C maior?",
    opcoes: ["I - V", "V - I", "IV - I", "V - VI"],
    resposta: 0,
    explicacoes: [
      "Correto. A semicadencia termina em dominante, deixando expectativa de continuacao.",
      "Incorreto. V-I e fechamento autentico, nao semicadencial.",
      "Incorreto. IV-I e fechamento plagal.",
      "Incorreto. V-VI e resolucao deceptiva.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "funcao",
    topico: "harmonia-funcional",
    pergunta: "Qual funcao harmonica tende a criar maior expectativa de resolucao?",
    opcoes: ["Tonica", "Subdominante", "Dominante", "Relativa"],
    resposta: 2,
    explicacoes: [
      "Incorreto. Tonica satisfaz a resolucao.",
      "Incorreto. Subdominante prepara, mas nao maximiza a tensao.",
      "Correto. Dominante concentra tensao e pede retorno para a tonica.",
      "Incorreto. Relativa nao e funcao principal de tensao maxima.",
    ],
  },
  {
    nivel: "facil",
    tema: "harmonia",
    subtema: "campo_harmonico",
    topico: "harmonia-funcional",
    pergunta: "Na tonalidade de C maior, qual acorde e o III grau?",
    opcoes: ["Dm", "Em", "F", "Am"],
    resposta: 1,
    explicacoes: [
      "Incorreto. Dm e II grau.",
      "Correto. Em e o III grau em C maior.",
      "Incorreto. F e IV grau.",
      "Incorreto. Am e VI grau.",
    ],
  },
];

perguntas.push(...harmonia_extra);

module.exports = { perguntas, TOPICOS };
