const perguntas = [
  // NIVEL FACIL
  { nivel: "facil", pergunta: "O que e musica?", opcoes: ["Organizacao de sons e silencio no tempo", "Som aleatorio", "Apenas ritmo", "Apenas melodia"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e som na musica?", opcoes: ["Vibracao percebida pelo ouvido", "Imagem", "Movimento", "Silencio"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e silencio na musica?", opcoes: ["Ausencia de som", "Som forte", "Nota longa", "Ritmo"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e ritmo?", opcoes: ["Organizacao dos sons no tempo", "Altura do som", "Volume", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e melodia?", opcoes: ["Sequencia de notas no tempo", "Varios sons ao mesmo tempo", "Silencio", "Batida"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e harmonia?", opcoes: ["Combinacao de sons simultaneos", "Uma unica nota", "Ritmo", "Silencio"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e intensidade?", opcoes: ["Forca do som", "Altura", "Tempo", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e altura do som?", opcoes: ["Grave ou agudo", "Forte ou fraco", "Rapido ou lento", "Curto ou longo"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e duracao?", opcoes: ["Tempo que o som permanece", "Altura", "Volume", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e timbre?", opcoes: ["Caracteristica que diferencia os sons", "Altura", "Tempo", "Volume"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e andamento?", opcoes: ["Velocidade da musica", "Altura", "Volume", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e pulsacao?", opcoes: ["Batida regular da musica", "Altura", "Nota", "Volume"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e compasso?", opcoes: ["Organizacao dos tempos em grupos", "Altura", "Timbre", "Nota"], resposta: 0 },
  { nivel: "facil", pergunta: "O que indica o compasso?", opcoes: ["Quantidade de tempos", "Altura", "Volume", "Timbre"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e pentagrama?", opcoes: ["Conjunto de cinco linhas", "Conjunto de notas", "Ritmo", "Instrumento"], resposta: 0 },
  { nivel: "facil", pergunta: "Para que serve o pentagrama?", opcoes: ["Escrever musica", "Aumentar o som", "Marcar ritmo", "Afinar instrumento"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e clave?", opcoes: ["Simbolo que define a altura das notas", "Figura ritmica", "Compasso", "Silencio"], resposta: 0 },
  { nivel: "facil", pergunta: "Para que serve a clave de Sol?", opcoes: ["Definir notas agudas", "Definir ritmo", "Definir volume", "Definir silencio"], resposta: 0 },
  { nivel: "facil", pergunta: "Para que serve a clave de Fa?", opcoes: ["Definir notas graves", "Definir ritmo", "Definir volume", "Definir silencio"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e nota musical?", opcoes: ["Representacao de um som", "Silencio", "Ritmo", "Compasso"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e figura musical?", opcoes: ["Representacao da duracao do som", "Altura", "Timbre", "Volume"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e pausa?", opcoes: ["Representacao do silencio", "Som forte", "Nota longa", "Altura"], resposta: 0 },
  { nivel: "facil", pergunta: "Para que servem as figuras musicais?", opcoes: ["Indicar duracao dos sons", "Indicar altura", "Indicar timbre", "Indicar volume"], resposta: 0 },
  { nivel: "facil", pergunta: "O que e escala musical?", opcoes: ["Sequencia de notas organizadas", "Ritmo", "Silencio", "Volume"], resposta: 0 },
  { nivel: "facil", pergunta: "Quantas linhas tem o pentagrama?", opcoes: ["5", "4", "6", "7"], resposta: 0 },

  // NIVEL MEDIO
  { nivel: "medio", pergunta: "Quantos semitons existem em uma oitava?", opcoes: ["6", "8", "12", "14"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantos semitons tem um tom?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantos semitons tem um semitom?", opcoes: ["1", "2", "3", "4"], resposta: 0 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Re?", opcoes: ["1 semitom", "1 tom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual intervalo entre Mi e Fa?", opcoes: ["1 tom", "1 semitom", "2 tons", "3 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantos graus tem a escala diatonica?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "medio", pergunta: "Qual e a formula da escala maior?", opcoes: ["T T ST T T T ST", "T ST T T ST T T", "ST T T T ST T T", "T T T ST T ST T"], resposta: 0 },
  { nivel: "medio", pergunta: "Quantos tempos tem o compasso 4/4?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantos tempos tem o compasso 3/4?", opcoes: ["2", "3", "4", "5"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual figura vale 1 tempo no 4/4?", opcoes: ["Semibreve", "Minima", "Seminima", "Colcheia"], resposta: 2 },
  { nivel: "medio", pergunta: "Quantas colcheias cabem em uma seminima?", opcoes: ["1", "2", "3", "4"], resposta: 1 },
  { nivel: "medio", pergunta: "O sustenido (#) altera:", opcoes: ["1 tom", "1 semitom acima", "1 semitom abaixo", "2 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "O bemol (b) altera:", opcoes: ["1 tom", "1 semitom abaixo", "1 semitom acima", "2 tons"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantas linhas tem a pauta?", opcoes: ["4", "5", "6", "7"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual clave indica sons graves?", opcoes: ["Sol", "Fa", "Do", "Neutra"], resposta: 1 },
  { nivel: "medio", pergunta: "Quantas seminimas cabem em uma semibreve?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Mi?", opcoes: ["Segunda", "Terca", "Quarta", "Quinta"], resposta: 1 },
  { nivel: "medio", pergunta: "Qual intervalo entre Do e Sol?", opcoes: ["Quarta", "Quinta", "Sexta", "Setima"], resposta: 1 },

  // NIVEL DIFICIL
  { nivel: "dificil", pergunta: "Quantos tons tem a escala maior?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "dificil", pergunta: "Quantos tons tem a escala menor natural?", opcoes: ["3", "4", "5", "6"], resposta: 1 },
  { nivel: "dificil", pergunta: "Quantos semitons tem a escala menor natural?", opcoes: ["10", "11", "12", "7"], resposta: 2 },
  { nivel: "dificil", pergunta: "Qual e a formula da escala menor natural?", opcoes: ["T ST T T ST T T", "T T ST T T T ST", "ST T T ST T T T", "T T T ST T ST T"], resposta: 0 },
  { nivel: "dificil", pergunta: "Uma triade tem quantas notas?", opcoes: ["2", "3", "4", "5"], resposta: 1 },
  { nivel: "dificil", pergunta: "Triade maior possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 0 },
  { nivel: "dificil", pergunta: "Triade menor possui:", opcoes: ["Terca maior", "Terca menor", "Quarta", "Segunda"], resposta: 1 },
  { nivel: "dificil", pergunta: "O V grau tem funcao:", opcoes: ["Tonica", "Dominante", "Subdominante", "Relativa"], resposta: 1 },
  { nivel: "dificil", pergunta: "O I grau tem funcao:", opcoes: ["Dominante", "Tonica", "Subdominante", "Sensivel"], resposta: 1 },
  { nivel: "dificil", pergunta: "Cadencia V-I e:", opcoes: ["Imperfeita", "Perfeita", "Plagal", "Deceptiva"], resposta: 1 },
  { nivel: "dificil", pergunta: "Quantos semitons tem uma quinta justa?", opcoes: ["5", "6", "7", "8"], resposta: 2 },
  { nivel: "dificil", pergunta: "Quantos semitons tem uma terca maior?", opcoes: ["2", "3", "4", "5"], resposta: 2 },
  { nivel: "dificil", pergunta: "O que e enarmonia?", opcoes: ["Mesmo som, nomes diferentes", "Notas diferentes", "Intervalos iguais", "Acordes iguais"], resposta: 0 },
  { nivel: "dificil", pergunta: "O que e modulacao?", opcoes: ["Mudanca de ritmo", "Mudanca de tonalidade", "Mudanca de intensidade", "Mudanca de timbre"], resposta: 1 },
];

module.exports = { perguntas };
